name: Lint Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install NodeJS Packages
        run: npm ci

      - name: Lint Code Base
        run: npm test
